### ISSUE TITLE
Firmware requirement

### ISSUE THREAD

**Issue by bakroistvan** [aagallag/hid_gadget_test#2]
Hi

Which "official" firmware is required? (http://flash.getchip.com/)

If there is none, how can I build build one myself?

**Comment by aagallag** [comment]
Hey there,

It's been a while since I've played with my CHIP, so I can't tell you which, if any, of the official firmware builds have support for the HID gadget.

When I was originally working on this, none of the official firmware builds had support.  So I used the Yocto project to compile a CHIP distro that included HID support.

If you are interested in getting familiar with the Yocto Project, you can compile my usb_hid_gadget branch and it will automatically include the HID gadget.  However, that's a pretty old branch, so it's running old version of kernel, firmware, ect.  https://github.com/aagallag/meta-sunxi/tree/usb_hid_gadget

Or if you are interested in enabling it for the official buildroot distro, take a look at this commit specifically: https://github.com/aagallag/meta-sunxi/commit/f710315bc14769f30f5a1c97ee92b0c736a963a5

**Comment by bakroistvan** [comment]
I am running into difficulties to build the image and get /dev/hidg0.

First I flash with the original 4.4 image.
I am doing the following steps to compile the kernel:
http://www.instructables.com/id/CHIP-USB-OTG-Ethernet-Gadget/

I change the following configs:
http://www.instructables.com/files/orig/F5V/UBWI/IJ4MK3AX/F5VUBWIIJ4MK3AX.png

Ethernet Gadget --> off
Serial Gadget --> off
HID Gadget --> on

than I compile the kernel. I copy the results to the CHIP:

```
cd ~/CHIP-buildroot/output/images
scp -r * root@192.168.0.###:/boot/
cd ~/CHIP-buildroot/output/target/lib/modules
scp -r * root@192.168.0.###:/lib/modules
```

After restart there is no /dev/hidg0.

Could you help me what am I missing?

**Comment by aagallag** [comment]
Have you applied the hidgadget patch to the kernel?

You can apply the patch with:

```
wget https://raw.githubusercontent.com/aagallag/meta-sunxi/f710315bc14769f30f5a1c97ee92b0c736a963a5/recipes-kernel/linux/linux-chip/usb_gadget.patch
patch -p1 < usb_gadget.patch
```

More info: https://www.kernel.org/doc/Documentation/usb/gadget_hid.txt
